services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto-meter
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    command: node_modules/.bin/nodemon -L --inspect=5555 index.js
    volumes:
      - ./:/usr/src/app
